language: python

python:
    - 3.4
    - 3.5
    - 3.5-dev
    - &latest_py3 3.6
    - 3.6-dev

jobs:
    include:
        - stage: Deploy
          if: tag IS present
          python: *latest_py3
          install:
              - pip install -U pip
              - pip install -r requirements.txt
          script: skip
          deploy:
              provider: pypi
              on:
                  tags: true
                  all_branches: true
              user: ganda
              password:
                  secure: EmGT3gsaXf+pLtOearaMWo/CedBS31qdd5eu1vv2FQ0dzKesG8qe+97qmoL8NyJxkl6PRblR//06e7OVa94MaC5TOJZddCWKktyK0yaeqAKXzAE4xixA7RD1UFQRKjfOdWwC670tK2ca/xTdlMfGwCL0mKVW/A33TxAMS0gLq8fe9iUacbWQM/DwpezdaQgoaOktU2NFv2UJfJfb9XOIjhlG9kbpC7fzeaWMK5dukl+geQoKKDLSS2lkc5/5nXduoznDgTGVxXq9sT18uti3wSXfQEqEt8M+9IUmpE7CMEEPHXW3jATKHiUnLmbe81x8VLVfSwg5JF5h0XShMGUbMrg6Nc2h3wE97nTvpg/AJGqbLMnPEC5BSFV+SU/AkNz6WOCNUTLHhSZdoXbUarUFunMjMEADdwlIicFgnBjQJi/Uh6GqvpuRiHE+iGl3r7g3VD2VhcxR10Oyjv9kDAltOAHPm5DFfakML8HFY54e6mawoa7FMBD43jepR2MwljXz1XQAfs+PSZzRS0PucSL2L+NNTs25+e2TlVU79+87LhDjs2CJunavLPyDFDqqHGJiUVDBPGWI+0dF+FY0+dyMxJuFPER0sM6OLAZByCECjH7x5gtwuOocNQDh87XLJTeD9Vdl9vl0JBUfGeBRy0CIB1aoQfK8qZZmZG+MhGZJqBY=
              distributions: "sdist bdist_wheel"
              skip_cleanup: true
              skip_upload_docs: true

install:
    - pip install -U pip
    - pip install -r requirements.txt

script: 
    - tox -e check
